import type { StarterDefinition } from "./types";

export const annuityStarter = {
  id: "annuity",
  chooser: {
    eyebrow: "Foundation",
    description: "Show how household income, premium authorship, and an income floor connect.",
    accent: "mineral",
  },
  document: {
    schemaVersion: 1,
    id: "annuity",
    title: "Annuity Income Floor",
    asOf: "As of July 2026",
    style: "foundation",
    modules: [
      {
        id: "annuity-income",
        kind: "income",
        primitive: "ledger",
        position: { x: 56, y: 132 },
        width: 280,
        eyebrow: "Household income",
        title: "Existing income sources",
        rows: [
          { id: "annuity-pension-row", label: "Pension", value: "$4,800/mo gross" },
          {
            id: "annuity-social-security-row",
            label: "Social Security",
            value: "$5,420/mo gross",
          },
        ],
      },
      {
        id: "annuity-policy",
        kind: "specialty",
        primitive: "band",
        position: { x: 480, y: 128 },
        width: 360,
        eyebrow: "Contract illustration",
        title: "Illustrative annuity",
        rows: [
          { id: "annuity-fmv-row", label: "FMV", value: "$109,000" },
          {
            id: "annuity-income-rider-row",
            label: "Income rider",
            value: "$21,475/yr gross",
          },
        ],
        total: { label: "Illustrative premium", value: "$300,000" },
      },
      {
        id: "annuity-need",
        kind: "need",
        primitive: "roundel",
        position: { x: 1104, y: 464 },
        width: 280,
        eyebrow: "Income floor",
        title: "Household need",
        rows: [{ id: "annuity-need-row", label: "Monthly target", value: "$16,000/mo" }],
      },
      {
        id: "annuity-source",
        kind: "account",
        primitive: "plate",
        position: { x: 56, y: 452 },
        width: 300,
        eyebrow: "Potential source",
        title: "Investment account",
        subtitle: "Selected by the advisor",
        rows: [
          { id: "annuity-source-balance-row", label: "Current balance", value: "$250,000" },
          { id: "annuity-source-range-row", label: "Planned range", value: "$20,000–?" },
        ],
      },
      {
        id: "annuity-plan",
        kind: "note",
        primitive: "frame",
        position: { x: 438, y: 420 },
        width: 340,
        eyebrow: "Advisor-authored plan",
        title: "Premium plan",
        rows: [
          {
            id: "annuity-planned-premium-row",
            label: "Planned premium",
            value: "$300,000 — revised illustration",
          },
          { id: "annuity-advisor-entry-row", label: "Advisor entry", value: "$_____" },
        ],
        note: "Funding cadence is authored, not calculated.",
      },
      {
        id: "annuity-reserve",
        kind: "reserve",
        primitive: "tray",
        position: { x: 1028, y: 130 },
        width: 300,
        eyebrow: "Liquidity",
        title: "Short-term reserve",
        rows: [{ id: "annuity-reserve-row", label: "Available", value: "$90,000" }],
        note: "Displayed independently of the premium plan.",
      },
    ],
    flows: [
      {
        id: "annuity-income-need",
        source: "annuity-income",
        target: "annuity-need",
        relationship: "flow",
        route: "curved",
        labelTreatment: "filled",
        label: "Monthly income",
        cadence: { kind: "monthly", label: "Monthly" },
        waypoints: [
          { x: 350, y: 306 },
          { x: 930, y: 376 },
        ],
      },
      {
        id: "annuity-source-plan",
        source: "annuity-source",
        target: "annuity-plan",
        relationship: "planned",
        route: "straight",
        labelTreatment: "plain",
        label: "Funding source",
        cadence: { kind: "custom", label: "Advisor-selected funding source" },
        waypoints: [{ x: 388, y: 384 }],
      },
      {
        id: "annuity-plan-contract",
        source: "annuity-plan",
        target: "annuity-policy",
        relationship: "planned",
        route: "orthogonal",
        labelTreatment: "plate",
        label: "Premium schedule",
        cadence: { kind: "custom", label: "Monthly installments — advisor entered" },
        waypoints: [{ x: 650, y: 340 }],
      },
      {
        id: "annuity-contract-need",
        source: "annuity-policy",
        target: "annuity-need",
        relationship: "flow",
        route: "straight",
        labelTreatment: "filled",
        label: "$21,475/yr gross — income rider",
        cadence: { kind: "annual", label: "Annual" },
        waypoints: [{ x: 960, y: 420 }],
      },
      {
        id: "annuity-reserve-need",
        source: "annuity-reserve",
        target: "annuity-need",
        relationship: "flow",
        route: "orthogonal",
        labelTreatment: "plate",
        label: "Reserve available",
        cadence: { kind: "as-needed", label: "As needed" },
        waypoints: [{ x: 1180, y: 386 }],
      },
      {
        id: "annuity-contract-reserve",
        source: "annuity-policy",
        target: "annuity-reserve",
        relationship: "association",
        route: "curved",
        labelTreatment: "plain",
        label: "Contract context",
        cadence: { kind: "custom", label: "Liquidity context" },
        waypoints: [{ x: 930, y: 218 }],
      },
    ],
    presentation: [
      {
        id: "overview",
        title: "Overview",
        moduleIds: [
          "annuity-income",
          "annuity-policy",
          "annuity-need",
          "annuity-source",
          "annuity-plan",
          "annuity-reserve",
        ],
        flowIds: [
          "annuity-income-need",
          "annuity-source-plan",
          "annuity-plan-contract",
          "annuity-contract-need",
          "annuity-reserve-need",
          "annuity-contract-reserve",
        ],
      },
      {
        id: "annuity-step-1",
        title: "Establish household income need",
        moduleIds: ["annuity-income", "annuity-need"],
        flowIds: ["annuity-income-need"],
      },
      {
        id: "annuity-step-2",
        title: "Identify funding sources",
        moduleIds: ["annuity-source", "annuity-plan"],
        flowIds: ["annuity-source-plan"],
      },
      {
        id: "annuity-step-3",
        title: "Author premium schedule",
        moduleIds: ["annuity-plan", "annuity-policy"],
        flowIds: ["annuity-plan-contract"],
      },
      {
        id: "annuity-step-4",
        title: "Review contract and rider",
        moduleIds: ["annuity-policy", "annuity-reserve"],
        flowIds: ["annuity-contract-reserve"],
      },
      {
        id: "annuity-step-5",
        title: "Connect income floor to need",
        moduleIds: ["annuity-policy", "annuity-need"],
        flowIds: ["annuity-contract-need"],
      },
    ],
  },
} satisfies StarterDefinition;
