import type { StarterDefinition } from "./types";

const modules = [
  {
    id: "retirement-income",
    kind: "income" as const,
    primitive: "ledger" as const,
    position: { x: 40, y: 20 },
    width: 250,
    eyebrow: "Income sources",
    title: "What arrives each month",
    rows: [
      {
        id: "retirement-income-social-security",
        label: "Social Security",
        value: "$6,400/mo gross",
      },
      { id: "retirement-income-rental", label: "Rental income", value: "$4,200/mo gross" },
      { id: "retirement-income-consulting", label: "Consulting", value: "~$3,000/mo" },
    ],
    total: { label: "After tax — advisor summary", value: "~$11,800/mo" },
  },
  {
    id: "retirement-need",
    kind: "need" as const,
    primitive: "roundel" as const,
    position: { x: 40, y: 520 },
    width: 250,
    eyebrow: "Household need",
    title: "Core lifestyle",
    rows: [],
    total: { label: "Monthly income need", value: "~$16,000/mo" },
  },
  {
    id: "retirement-reserve",
    kind: "reserve" as const,
    primitive: "tray" as const,
    position: { x: 400, y: 470 },
    width: 270,
    eyebrow: "Liquidity",
    title: "Short-term reserve",
    subtitle: "18 months of planned spending",
    rows: [],
    total: { label: "Balance", value: "$240,000" },
    note: "Refilled from the joint account.",
  },
  {
    id: "retirement-joint",
    kind: "account" as const,
    primitive: "plate" as const,
    position: { x: 350, y: 20 },
    width: 300,
    eyebrow: "Taxable — trust",
    title: "Joint after-tax account",
    subtitle: "Hartwell Family Trust — tax-managed",
    rows: [
      {
        id: "retirement-joint-highlight",
        label: "Highlighted position — HTW Industrial",
        value: "~$120,000",
      },
    ],
    total: { label: "Balance", value: "~$1,480,000" },
    note: "Refills the short-term reserve periodically.",
  },
  {
    id: "retirement-annuity",
    kind: "specialty" as const,
    primitive: "band" as const,
    position: { x: 710, y: 470 },
    width: 280,
    eyebrow: "Annuity contract",
    title: "JNL Fixed Index Annuity",
    rows: [
      { id: "retirement-annuity-fmv", label: "FMV", value: "$109,000" },
      { id: "retirement-annuity-rider", label: "Income rider", value: "$21,475/yr gross" },
    ],
  },
  {
    id: "retirement-giving",
    kind: "charitable" as const,
    primitive: "band" as const,
    position: { x: 740, y: 20 },
    width: 260,
    eyebrow: "Donor-advised fund",
    title: "Hartwell Giving Fund",
    rows: [{ id: "retirement-giving-grants", label: "Annual grants", value: "~$25,000" }],
    total: { label: "Balance", value: "$185,000" },
  },
  {
    id: "retirement-ira",
    kind: "account" as const,
    primitive: "plate" as const,
    position: { x: 1100, y: 20 },
    width: 290,
    eyebrow: "Tax-deferred",
    title: "Traditional IRA",
    subtitle: "Morgan Hartwell — rollover",
    rows: [
      { id: "retirement-ira-rmd", label: "2026 RMD", value: "$37,818 gross" },
      { id: "retirement-ira-withholding", label: "After W/H", value: "$25,471" },
    ],
    total: { label: "Balance", value: "$2,436,000" },
  },
  {
    id: "retirement-roth",
    kind: "account" as const,
    primitive: "roundel" as const,
    position: { x: 1110, y: 350 },
    width: 240,
    eyebrow: "Tax-preferred",
    title: "Roth IRA",
    subtitle: "Dana Hartwell",
    rows: [],
    total: { label: "Balance", value: "$291,000" },
    note: "No lifetime RMDs — last money out.",
  },
  {
    id: "retirement-trust",
    kind: "specialty" as const,
    primitive: "frame" as const,
    position: { x: 1040, y: 560 },
    width: 300,
    eyebrow: "Insurance trust",
    title: "Irrevocable Life Insurance Trust",
    rows: [
      { id: "retirement-trust-benefit", label: "Death benefit", value: "$1,000,000" },
      { id: "retirement-trust-cash", label: "Cash value", value: "$71,000" },
    ],
  },
];

const flows = [
  {
    id: "retirement-income-flow",
    source: "retirement-income",
    target: "retirement-need",
    relationship: "flow" as const,
    route: "curved" as const,
    labelTreatment: "filled" as const,
    label: "~$11,800 monthly — after tax",
    cadence: { kind: "monthly" as const, label: "Monthly" },
    waypoints: [{ x: 165, y: 400 }],
  },
  {
    id: "retirement-reserve-flow",
    source: "retirement-reserve",
    target: "retirement-need",
    relationship: "flow" as const,
    route: "orthogonal" as const,
    labelTreatment: "plate" as const,
    label: "As needed",
    cadence: { kind: "as-needed" as const, label: "As needed" },
    waypoints: [{ x: 345, y: 430 }],
  },
  {
    id: "retirement-refill-flow",
    source: "retirement-joint",
    target: "retirement-reserve",
    relationship: "flow" as const,
    route: "curved" as const,
    labelTreatment: "plain" as const,
    label: "Periodic refill",
    cadence: { kind: "custom" as const, label: "Refills periodically" },
    waypoints: [{ x: 515, y: 370 }],
  },
  {
    id: "retirement-rmd-flow",
    source: "retirement-ira",
    target: "retirement-need",
    relationship: "flow" as const,
    route: "orthogonal" as const,
    labelTreatment: "plate" as const,
    label: "2026 RMD — $37,818 gross",
    secondaryLabel: "After W/H: $25,471",
    cadence: { kind: "annual" as const, label: "Annual" },
    waypoints: [
      { x: 1030, y: 310 },
      { x: 1020, y: 735 },
      { x: 300, y: 736 },
    ],
  },
  {
    id: "retirement-annuity-flow",
    source: "retirement-annuity",
    target: "retirement-need",
    relationship: "flow" as const,
    route: "straight" as const,
    labelTreatment: "filled" as const,
    label: "$21,475/yr — income rider",
    secondaryLabel: "$21,475/yr gross",
    cadence: { kind: "annual" as const, label: "Annual" },
    waypoints: [
      { x: 820, y: 710 },
      { x: 300, y: 711 },
    ],
  },
  {
    id: "retirement-qcd-flow",
    source: "retirement-ira",
    target: "retirement-giving",
    relationship: "planned" as const,
    route: "orthogonal" as const,
    labelTreatment: "plain" as const,
    label: "QCD — Up to $105,000",
    cadence: { kind: "annual" as const, label: "Annual" },
    waypoints: [{ x: 1220, y: 310 }],
  },
  {
    id: "retirement-legacy-flow",
    source: "retirement-trust",
    target: "retirement-need",
    relationship: "association" as const,
    route: "straight" as const,
    labelTreatment: "plain" as const,
    label: "Legacy context",
    cadence: { kind: "custom" as const, label: "Estate-plan context" },
    waypoints: [
      { x: 980, y: 690 },
      { x: 300, y: 730 },
    ],
  },
];

export const retirementStarter = {
  id: "retirement",
  chooser: {
    eyebrow: "Private Ledger",
    description:
      "Trace recurring income, reserves, required distributions, and the household need.",
    accent: "ochre",
  },
  document: {
    schemaVersion: 1,
    id: "retirement",
    title: "Retirement Income",
    asOf: "As of July 2026",
    style: "private-ledger",
    modules,
    flows,
    presentation: [
      {
        id: "overview",
        title: "Overview",
        moduleIds: modules.map(({ id }) => id),
        flowIds: flows.map(({ id }) => id),
      },
      {
        id: "retirement-income-to-need",
        title: "Income to household need",
        moduleIds: ["retirement-income", "retirement-need"],
        flowIds: ["retirement-income-flow"],
      },
      {
        id: "retirement-reserve-withdrawals",
        title: "Reserve withdrawals",
        moduleIds: ["retirement-reserve", "retirement-need"],
        flowIds: ["retirement-reserve-flow"],
      },
      {
        id: "retirement-reserve-replenishment",
        title: "Reserve replenishment",
        moduleIds: ["retirement-joint", "retirement-reserve"],
        flowIds: ["retirement-refill-flow"],
      },
      {
        id: "retirement-rmd",
        title: "2026 RMD",
        moduleIds: ["retirement-ira", "retirement-need"],
        flowIds: ["retirement-rmd-flow"],
      },
      {
        id: "retirement-annuity-income",
        title: "Annuity income",
        moduleIds: ["retirement-annuity", "retirement-need"],
        flowIds: ["retirement-annuity-flow"],
      },
    ],
  },
} satisfies StarterDefinition;
