import type { StarterDefinition } from "./types";

export const rmdStarter = {
  id: "rmd",
  chooser: {
    eyebrow: "Distribution Registry",
    description:
      "Explain the annual distribution sequence without pretending to calculate its outcome.",
    accent: "pine",
  },
  document: {
    schemaVersion: 2,
    id: "rmd",
    title: "RMD & Withholding",
    asOf: "As of July 2026",
    style: "distribution-registry",
    defaultCadence: "annual",
    modules: [
      {
        id: "rmd-source",
        kind: "account",
        primitive: "ledger",
        position: { x: 48, y: 274 },
        width: 240,
        height: 210,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "account",
        swatch: "base",
        zIndex: 0,
        eyebrow: "Distribution source",
        title: "Traditional IRA",
        rows: [
          { id: "rmd-source-balance", label: "Balance", value: "$1,240,000" },
          {
            id: "rmd-source-distribution",
            label: "2026 distribution",
            value: "$48,600 est.",
          },
        ],
      },
      {
        id: "rmd-instruction",
        kind: "note",
        primitive: "plate",
        position: { x: 424, y: 274 },
        width: 270,
        height: 170,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "note",
        swatch: "base",
        zIndex: 1,
        eyebrow: "Annual register",
        title: "2026 distribution instruction",
        rows: [],
        note: "Advisor-authored amount and sequence",
      },
      {
        id: "rmd-charitable",
        kind: "charitable",
        primitive: "band",
        position: { x: 735, y: 42 },
        width: 260,
        height: 190,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "charitable",
        swatch: "base",
        zIndex: 2,
        eyebrow: "Charitable direction",
        title: "Qualified charitable distribution",
        rows: [
          {
            id: "rmd-charitable-gift",
            label: "Planned gift",
            value: "Up to $105,000 — advisor entered",
          },
        ],
      },
      {
        id: "rmd-federal",
        kind: "note",
        primitive: "band",
        position: { x: 735, y: 274 },
        width: 240,
        height: 180,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "note",
        swatch: "base",
        zIndex: 3,
        eyebrow: "Tax instruction",
        title: "Federal withholding",
        rows: [{ id: "rmd-federal-entry", label: "Instruction", value: "__% / $_____" }],
      },
      {
        id: "rmd-state",
        kind: "note",
        primitive: "band",
        position: { x: 735, y: 506 },
        width: 240,
        height: 180,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "note",
        swatch: "base",
        zIndex: 4,
        eyebrow: "Tax instruction",
        title: "State withholding",
        rows: [{ id: "rmd-state-entry", label: "Instruction", value: "__% / $_____" }],
      },
      {
        id: "rmd-reserve",
        kind: "reserve",
        primitive: "tray",
        position: { x: 1044, y: 292 },
        width: 284,
        height: 190,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "reserve",
        swatch: "base",
        zIndex: 5,
        eyebrow: "Net destination",
        title: "Household reserve",
        rows: [
          {
            id: "rmd-reserve-deposit",
            label: "Net deposit",
            value: "$_____ — advisor entered",
          },
        ],
      },
      {
        id: "rmd-need",
        kind: "need",
        primitive: "roundel",
        position: { x: 1080, y: 526 },
        width: 248,
        height: 170,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "need",
        swatch: "base",
        zIndex: 6,
        eyebrow: "Household need",
        title: "Household need",
        rows: [],
        total: { label: "Monthly need", value: "$12,500/mo" },
      },
      {
        id: "rmd-review",
        kind: "note",
        primitive: "frame",
        position: { x: 1052, y: 38 },
        width: 328,
        height: 210,
        rotation: 0,
        priority: "standard",
        density: "standard",
        colorRole: "note",
        swatch: "base",
        zIndex: 7,
        eyebrow: "Year-end close",
        title: "Year-end records",
        rows: [
          { id: "rmd-review-1099r", label: "Form 1099-R", value: "Advisor review" },
          {
            id: "rmd-review-return",
            label: "Tax return",
            value: "Prepared outside Money Map",
          },
        ],
      },
    ],
    flows: [
      {
        id: "rmd-establish",
        source: "rmd-source",
        target: "rmd-instruction",
        relationship: "transfer",
        route: "straight",
        labelTreatment: "plain",
        label: "2026 distribution",
        cadence: { kind: "annual", label: "Annual" },
        labelPosition: { x: 356, y: 374 },
        waypoints: [],
      },
      {
        id: "rmd-qcd",
        source: "rmd-instruction",
        target: "rmd-charitable",
        relationship: "planned",
        route: "orthogonal",
        labelTreatment: "plate",
        label: "Qualified charitable distribution",
        cadence: { kind: "annual", label: "Annual" },
        labelPosition: { x: 560, y: 180 },
        waypoints: [{ x: 560, y: 180 }],
      },
      {
        id: "rmd-federal-withholding",
        source: "rmd-instruction",
        target: "rmd-federal",
        relationship: "planned",
        route: "orthogonal",
        labelTreatment: "filled",
        label: "Federal instruction",
        cadence: { kind: "annual", label: "Annual" },
        labelPosition: { x: 650, y: 380 },
        waypoints: [{ x: 650, y: 380 }],
      },
      {
        id: "rmd-state-withholding",
        source: "rmd-instruction",
        target: "rmd-state",
        relationship: "planned",
        route: "orthogonal",
        labelTreatment: "filled",
        label: "State instruction",
        cadence: { kind: "annual", label: "Annual" },
        labelPosition: { x: 520, y: 600 },
        waypoints: [{ x: 520, y: 600 }],
      },
      {
        id: "rmd-net-distribution",
        source: "rmd-instruction",
        target: "rmd-reserve",
        relationship: "transfer",
        route: "orthogonal",
        labelTreatment: "plate",
        label: "Net distribution — advisor entered",
        cadence: { kind: "annual", label: "Annual" },
        labelPosition: { x: 700, y: 480 },
        waypoints: [
          { x: 700, y: 480 },
          { x: 1004, y: 470 },
        ],
      },
      {
        id: "rmd-household-need",
        source: "rmd-reserve",
        target: "rmd-need",
        relationship: "transfer",
        route: "curved",
        labelTreatment: "plain",
        label: "Household transfer",
        cadence: { kind: "monthly", label: "Monthly" },
        labelPosition: { x: 1226, y: 500 },
        waypoints: [{ x: 1226, y: 500 }],
      },
      {
        id: "rmd-year-end-review",
        source: "rmd-instruction",
        target: "rmd-review",
        relationship: "planned",
        route: "straight",
        labelTreatment: "plain",
        label: "Review distribution records",
        cadence: { kind: "custom", label: "At year-end" },
        labelPosition: { x: 559, y: 690 },
        waypoints: [
          { x: 559, y: 690 },
          { x: 1010, y: 710 },
          { x: 1010, y: 500 },
          { x: 1400, y: 500 },
          { x: 1400, y: 130 },
        ],
      },
    ],
    presentation: [
      {
        id: "overview",
        title: "Overview",
        moduleIds: [
          "rmd-source",
          "rmd-instruction",
          "rmd-charitable",
          "rmd-federal",
          "rmd-state",
          "rmd-reserve",
          "rmd-need",
          "rmd-review",
        ],
        flowIds: [
          "rmd-establish",
          "rmd-qcd",
          "rmd-federal-withholding",
          "rmd-state-withholding",
          "rmd-net-distribution",
          "rmd-household-need",
          "rmd-year-end-review",
        ],
      },
      {
        id: "rmd-step-1",
        title: "Establish 2026 distribution",
        moduleIds: ["rmd-source", "rmd-instruction"],
        flowIds: ["rmd-establish"],
      },
      {
        id: "rmd-step-2",
        title: "Direct qualified charitable distribution",
        moduleIds: ["rmd-instruction", "rmd-charitable"],
        flowIds: ["rmd-qcd"],
      },
      {
        id: "rmd-step-3",
        title: "Record withholding instructions",
        moduleIds: ["rmd-instruction", "rmd-federal", "rmd-state"],
        flowIds: ["rmd-federal-withholding", "rmd-state-withholding"],
      },
      {
        id: "rmd-step-4",
        title: "Route net distribution",
        moduleIds: ["rmd-instruction", "rmd-reserve", "rmd-need"],
        flowIds: ["rmd-net-distribution", "rmd-household-need"],
      },
      {
        id: "rmd-step-5",
        title: "Review year-end records",
        moduleIds: ["rmd-instruction", "rmd-review"],
        flowIds: ["rmd-year-end-review"],
      },
    ],
  },
} satisfies StarterDefinition;
