import type { MoneyMapFlow, MoneyMapModule } from "../model/types";
import type { StarterDefinition } from "./types";

const modules: MoneyMapModule[] = [
  {
    id: "roth-source",
    kind: "account",
    primitive: "frame",
    position: { x: 60, y: 90 },
    width: 270,
    eyebrow: "Conversion source",
    title: "Traditional IRA",
    rows: [{ id: "roth-source-balance", label: "Display balance", value: "~$860,000" }],
    note: "Source account named by the advisor.",
  },
  {
    id: "roth-2026",
    kind: "specialty",
    primitive: "band",
    position: { x: 480, y: 82 },
    width: 300,
    eyebrow: "Current-year stage",
    title: "2026 conversion window",
    rows: [{ id: "roth-2026-range", label: "Planned range", value: "$75,000–$125,000" }],
    note: "Range is displayed exactly as authored.",
  },
  {
    id: "roth-destination",
    kind: "account",
    primitive: "plate",
    position: { x: 1090, y: 90 },
    width: 280,
    eyebrow: "Conversion destination",
    title: "Roth IRA",
    rows: [{ id: "roth-destination-balance", label: "Display balance", value: "$291,000" }],
    note: "Destination for advisor-directed conversions.",
  },
  {
    id: "roth-tax-reserve",
    kind: "reserve",
    primitive: "roundel",
    position: { x: 430, y: 420 },
    width: 250,
    eyebrow: "Outside funds",
    title: "Outside tax reserve",
    rows: [{ id: "roth-tax-reserve-entry", label: "Advisor entry", value: "$_____" }],
    note: "Payment source is identified separately from the conversion range.",
  },
  {
    id: "roth-guardrails",
    kind: "note",
    primitive: "ledger",
    position: { x: 740, y: 400 },
    width: 320,
    eyebrow: "Review before action",
    title: "Planning guardrails",
    rows: [
      { id: "roth-guardrail-tax", label: "Tax review", value: "Advisor directed" },
      {
        id: "roth-guardrail-medicare",
        label: "Medicare review",
        value: "Discussed separately",
      },
      { id: "roth-guardrail-result", label: "Planning status", value: "No calculated result" },
    ],
  },
  {
    id: "roth-2027",
    kind: "specialty",
    primitive: "band",
    position: { x: 1090, y: 430 },
    width: 280,
    eyebrow: "Future-year stage",
    title: "2027 conversion window",
    rows: [{ id: "roth-2027-timing", label: "Timing", value: "After year-end review" }],
    note: "A separate planning window, not a calculated continuation.",
  },
  {
    id: "roth-liquidity",
    kind: "reserve",
    primitive: "tray",
    position: { x: 60, y: 460 },
    width: 260,
    eyebrow: "Household reserve",
    title: "Household liquidity",
    rows: [{ id: "roth-liquidity-availability", label: "Availability", value: "As needed" }],
    note: "Shown for planning visibility only.",
  },
];

const flows: MoneyMapFlow[] = [
  {
    id: "roth-source-to-2026",
    source: "roth-source",
    target: "roth-2026",
    relationship: "planned",
    route: "curved",
    labelTreatment: "filled",
    label: "2026 conversion",
    cadence: { kind: "annual", label: "Annual" },
    waypoints: [],
  },
  {
    id: "roth-2026-to-destination",
    source: "roth-2026",
    target: "roth-destination",
    relationship: "flow",
    route: "straight",
    labelTreatment: "plate",
    label: "To Roth IRA",
    cadence: { kind: "one-time", label: "One-time" },
    waypoints: [],
  },
  {
    id: "roth-tax-reserve-to-2026",
    source: "roth-tax-reserve",
    target: "roth-2026",
    relationship: "association",
    route: "orthogonal",
    labelTreatment: "plain",
    label: "Outside reserve",
    cadence: { kind: "custom", label: "Alongside each conversion" },
    waypoints: [{ x: 640, y: 350 }],
  },
  {
    id: "roth-2026-to-guardrails",
    source: "roth-2026",
    target: "roth-guardrails",
    relationship: "association",
    route: "straight",
    labelTreatment: "plain",
    label: "Advisor review",
    cadence: { kind: "custom", label: "Advisor tax review" },
    waypoints: [{ x: 850, y: 360 }],
  },
  {
    id: "roth-source-to-2027",
    source: "roth-source",
    target: "roth-2027",
    relationship: "planned",
    route: "orthogonal",
    labelTreatment: "plate",
    label: "2027 window",
    cadence: { kind: "annual", label: "Annual" },
    waypoints: [
      { x: 360, y: 310 },
      { x: 1030, y: 310 },
    ],
  },
  {
    id: "roth-2027-to-destination",
    source: "roth-2027",
    target: "roth-destination",
    relationship: "flow",
    route: "curved",
    labelTreatment: "filled",
    label: "To Roth IRA",
    cadence: { kind: "one-time", label: "One-time" },
    waypoints: [{ x: 1300, y: 385 }],
  },
  {
    id: "roth-liquidity-to-tax-reserve",
    source: "roth-liquidity",
    target: "roth-tax-reserve",
    relationship: "association",
    route: "straight",
    labelTreatment: "plain",
    label: "Reserve context",
    cadence: { kind: "as-needed", label: "As needed" },
    waypoints: [],
  },
  {
    id: "roth-liquidity-to-source",
    source: "roth-liquidity",
    target: "roth-source",
    relationship: "association",
    route: "curved",
    labelTreatment: "plate",
    label: "Monthly review",
    secondaryLabel: "Display-only relationship",
    cadence: { kind: "monthly", label: "Monthly" },
    waypoints: [{ x: 185, y: 350 }],
  },
];

export const rothStarter = {
  id: "roth",
  chooser: {
    eyebrow: "Conversion Path",
    description:
      "Stage a multi-year conversion story across source, reserve, review, and destination accounts.",
    accent: "aubergine",
  },
  document: {
    schemaVersion: 1,
    id: "roth",
    title: "Roth Conversion",
    asOf: "As of July 2026",
    style: "conversion-path",
    modules: [...modules],
    flows: [...flows],
    presentation: [
      {
        id: "overview",
        title: "Overview",
        moduleIds: modules.map(({ id }) => id),
        flowIds: flows.map(({ id }) => id),
      },
      {
        id: "roth-step-1",
        title: "Establish source and destination",
        moduleIds: ["roth-source", "roth-2026", "roth-destination"],
        flowIds: ["roth-source-to-2026", "roth-2026-to-destination"],
      },
      {
        id: "roth-step-2",
        title: "Frame 2026 conversion range",
        moduleIds: ["roth-source", "roth-2026"],
        flowIds: ["roth-source-to-2026"],
      },
      {
        id: "roth-step-3",
        title: "Identify tax-payment source",
        moduleIds: ["roth-liquidity", "roth-tax-reserve", "roth-2026"],
        flowIds: ["roth-liquidity-to-tax-reserve", "roth-tax-reserve-to-2026"],
      },
      {
        id: "roth-step-4",
        title: "Review planning guardrails",
        moduleIds: ["roth-2026", "roth-guardrails"],
        flowIds: ["roth-2026-to-guardrails"],
      },
      {
        id: "roth-step-5",
        title: "Stage the 2027 window",
        moduleIds: ["roth-source", "roth-2027", "roth-destination"],
        flowIds: ["roth-source-to-2027", "roth-2027-to-destination"],
      },
    ],
  },
} satisfies StarterDefinition;
