import type { MoneyMapDocument, StarterId } from "../model/types";

function withOverview(document: Omit<MoneyMapDocument, "presentation">): MoneyMapDocument {
  return {
    ...document,
    presentation: [
      {
        id: "overview",
        title: "Overview",
        moduleIds: document.modules.map((module) => module.id),
        flowIds: document.flows.map((flow) => flow.id),
      },
    ],
  };
}

const scaffolds = {
  retirement: withOverview({
    schemaVersion: 1,
    id: "retirement",
    title: "Retirement Income",
    asOf: "As of July 2026",
    style: "private-ledger",
    modules: [
      {
        id: "retirement-income",
        kind: "income",
        primitive: "band",
        position: { x: 64, y: 84 },
        width: 260,
        eyebrow: "Recurring income",
        title: "Social Security",
        subtitle: "Hartwell household",
        rows: [{ id: "retirement-income-row", label: "Monthly benefit", value: "$5,420/mo" }],
        note: "Begins on the advisor-authored date.",
      },
      {
        id: "retirement-reserve",
        kind: "reserve",
        primitive: "ledger",
        position: { x: 412, y: 224 },
        width: 286,
        eyebrow: "Flexible reserve",
        title: "Traditional IRA",
        rows: [
          { id: "retirement-reserve-row", label: "Display balance", value: "~$1.18M" },
          { id: "retirement-rmd-row", label: "Annual distribution", value: "Advisor to enter" },
        ],
      },
      {
        id: "retirement-need",
        kind: "need",
        primitive: "tray",
        position: { x: 798, y: 104 },
        width: 276,
        eyebrow: "Household need",
        title: "Core lifestyle",
        rows: [{ id: "retirement-need-row", label: "Monthly target", value: "$12,500/mo" }],
        total: { label: "Planning posture", value: "Income sources + reserves" },
      },
    ],
    flows: [
      {
        id: "retirement-income-flow",
        source: "retirement-income",
        target: "retirement-need",
        relationship: "flow",
        route: "curved",
        labelTreatment: "plain",
        label: "$5,420/mo",
        cadence: { kind: "monthly", label: "Monthly" },
        waypoints: [],
      },
      {
        id: "retirement-reserve-flow",
        source: "retirement-reserve",
        target: "retirement-need",
        relationship: "planned",
        route: "orthogonal",
        labelTreatment: "plate",
        label: "As needed",
        secondaryLabel: "Advisor-directed withdrawals",
        cadence: { kind: "as-needed", label: "As needed" },
        waypoints: [{ x: 744, y: 316 }],
      },
    ],
  }),
  rmd: withOverview({
    schemaVersion: 1,
    id: "rmd",
    title: "RMD & Withholding",
    asOf: "As of July 2026",
    style: "distribution-registry",
    modules: [
      {
        id: "rmd-account",
        kind: "account",
        primitive: "ledger",
        position: { x: 72, y: 86 },
        width: 286,
        eyebrow: "Distribution source",
        title: "Traditional IRA",
        rows: [
          { id: "rmd-account-row", label: "Display balance", value: "$1,240,000" },
          { id: "rmd-distribution-row", label: "2026 distribution", value: "$48,600 est." },
        ],
      },
      {
        id: "rmd-tax",
        kind: "reserve",
        primitive: "plate",
        position: { x: 458, y: 82 },
        width: 246,
        eyebrow: "Withholding direction",
        title: "Federal & state",
        rows: [{ id: "rmd-tax-row", label: "Advisor entry", value: "__% / __%" }],
        note: "Display-only withholding instruction.",
      },
      {
        id: "rmd-destination",
        kind: "account",
        primitive: "tray",
        position: { x: 804, y: 230 },
        width: 280,
        eyebrow: "Net destination",
        title: "Household reserve",
        rows: [
          { id: "rmd-destination-row", label: "Deposit", value: "Remainder after withholding" },
        ],
      },
    ],
    flows: [
      {
        id: "rmd-tax-flow",
        source: "rmd-account",
        target: "rmd-tax",
        relationship: "flow",
        route: "orthogonal",
        labelTreatment: "filled",
        label: "Withhold per instruction",
        cadence: { kind: "annual", label: "Annual" },
        waypoints: [{ x: 406, y: 168 }],
      },
      {
        id: "rmd-net-flow",
        source: "rmd-account",
        target: "rmd-destination",
        relationship: "flow",
        route: "straight",
        labelTreatment: "plain",
        label: "Net distribution",
        cadence: { kind: "annual", label: "Annual" },
        waypoints: [],
      },
    ],
  }),
  annuity: withOverview({
    schemaVersion: 1,
    id: "annuity",
    title: "Annuity Income Floor",
    asOf: "As of July 2026",
    style: "foundation",
    modules: [
      {
        id: "annuity-source",
        kind: "account",
        primitive: "ledger",
        position: { x: 58, y: 100 },
        width: 280,
        eyebrow: "Source account",
        title: "Investment account",
        subtitle: "Available by advisor direction",
        rows: [
          { id: "annuity-source-row", label: "Current balance", value: "$250,000" },
          { id: "annuity-range-row", label: "Planned range", value: "$20,000–?" },
        ],
      },
      {
        id: "annuity-policy",
        kind: "income",
        primitive: "band",
        position: { x: 430, y: 104 },
        width: 304,
        eyebrow: "Income floor",
        title: "Illustrative annuity",
        rows: [
          {
            id: "annuity-premium-row",
            label: "Premium",
            value: "$300,000 \u2014 revised illustration",
          },
          { id: "annuity-income-row", label: "Monthly income", value: "~$11,800/mo" },
          { id: "annuity-placeholder-row", label: "Advisor entry", value: "$_____" },
        ],
        total: { label: "Illustrative premium", value: "$300,000" },
        note: "Amounts are advisor-authored display text.",
      },
      {
        id: "annuity-need",
        kind: "need",
        primitive: "plate",
        position: { x: 824, y: 138 },
        width: 248,
        eyebrow: "Household need",
        title: "Core spending",
        rows: [{ id: "annuity-need-row", label: "Monthly", value: "$_____" }],
      },
    ],
    flows: [
      {
        id: "annuity-funding-flow",
        source: "annuity-source",
        target: "annuity-policy",
        relationship: "planned",
        route: "orthogonal",
        labelTreatment: "plate",
        label: "$300,000 premium",
        secondaryLabel: "Advisor-authored illustration",
        cadence: { kind: "one-time", label: "One-time" },
        waypoints: [{ x: 384, y: 184 }],
      },
      {
        id: "annuity-income-flow",
        source: "annuity-policy",
        target: "annuity-need",
        relationship: "flow",
        route: "straight",
        labelTreatment: "plain",
        label: "~$11,800/mo",
        cadence: { kind: "monthly", label: "Monthly" },
        waypoints: [],
      },
    ],
  }),
  roth: withOverview({
    schemaVersion: 1,
    id: "roth",
    title: "Roth Conversion",
    asOf: "As of July 2026",
    style: "conversion-path",
    modules: [
      {
        id: "roth-source",
        kind: "account",
        primitive: "frame",
        position: { x: 64, y: 104 },
        width: 280,
        eyebrow: "Conversion source",
        title: "Traditional IRA",
        rows: [{ id: "roth-source-row", label: "Display balance", value: "~$860,000" }],
      },
      {
        id: "roth-reserve",
        kind: "reserve",
        primitive: "roundel",
        position: { x: 440, y: 258 },
        width: 252,
        eyebrow: "Outside reserve",
        title: "Tax reserve",
        rows: [{ id: "roth-reserve-row", label: "Available", value: "$_____" }],
        note: "Advisor identifies the payment source.",
      },
      {
        id: "roth-destination",
        kind: "account",
        primitive: "band",
        position: { x: 800, y: 102 },
        width: 286,
        eyebrow: "Long-term destination",
        title: "Roth IRA",
        rows: [
          { id: "roth-destination-row", label: "Planned conversion", value: "$75,000–$125,000" },
        ],
      },
    ],
    flows: [
      {
        id: "roth-conversion-flow",
        source: "roth-source",
        target: "roth-destination",
        relationship: "planned",
        route: "curved",
        labelTreatment: "filled",
        label: "Annual conversion window",
        cadence: { kind: "annual", label: "Annual" },
        waypoints: [],
      },
      {
        id: "roth-tax-flow",
        source: "roth-reserve",
        target: "roth-source",
        relationship: "association",
        route: "straight",
        labelTreatment: "plain",
        label: "Tax payment source",
        cadence: { kind: "custom", label: "Alongside each conversion" },
        waypoints: [],
      },
    ],
  }),
} satisfies Record<StarterId, MoneyMapDocument>;

export function getScaffoldDocument(id: StarterId): MoneyMapDocument {
  return scaffolds[id];
}
